services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      MONGODB_URI: mongodb://scout_mongo:27017
      MONGODB_DB: user_registration
      CORS_ALLOW_ORIGIN: '^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'
      APP_ENV: dev
    networks:
      - scout_net

networks:
  scout_net:
    external: true
